#!/usr/bin/env python3
"""Tests for enclave-closure-check.py — the CI measurement gate's parser and
traversal. Stdlib unittest only (CI runs it without installing anything):

    python3 -m unittest scripts/test_enclave_closure_check.py
"""
import importlib.util
import os
import tempfile
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("ecc", HERE / "enclave-closure-check.py")
ecc = importlib.util.module_from_spec(spec)
spec.loader.exec_module(ecc)

REG = "registry+https://github.com/rust-lang/crates.io-index"


def lock(*blocks: str) -> str:
    return "# This file is automatically @generated by Cargo.\nversion = 4\n\n" + "\n".join(blocks)


def pkg(name, version, source=None, deps=()):
    out = [f'[[package]]', f'name = "{name}"', f'version = "{version}"']
    if source:
        out.append(f'source = "{source}"')
    if deps:
        out.append("dependencies = [")
        out += [f' "{d}",' for d in deps]
        out.append("]")
    return "\n".join(out) + "\n"


class ParseAndClosure(unittest.TestCase):
    def test_closure_follows_versioned_and_unversioned_deps(self):
        text = lock(
            pkg("signer-enclave", "0.1.0", deps=["a", "b 2.0.0"]),
            pkg("a", "1.0.0", REG, deps=["c"]),
            pkg("b", "1.0.0", REG),          # NOT in closure: enclave pins b 2.0.0
            pkg("b", "2.0.0", REG),
            pkg("c", "0.3.0", REG),
            pkg("unrelated", "9.9.9", REG),
        )
        got = ecc.closure(ecc.parse_lock(text), "signer-enclave")
        self.assertEqual(got, [f"a 1.0.0 ({REG})", f"b 2.0.0 ({REG})", f"c 0.3.0 ({REG})"])

    def test_same_name_version_different_source_is_a_different_package(self):
        git = "git+https://github.com/example/c?rev=abc123#abc123"
        before = lock(pkg("signer-enclave", "0.1.0", deps=["c"]), pkg("c", "0.3.0", REG))
        after = lock(pkg("signer-enclave", "0.1.0", deps=["c"]), pkg("c", "0.3.0", git))
        a = ecc.closure(ecc.parse_lock(before), "signer-enclave")
        b = ecc.closure(ecc.parse_lock(after), "signer-enclave")
        self.assertNotEqual(a, b, "a registry→git replacement must change the closure identity")

    def test_git_revision_bump_changes_closure(self):
        g1 = "git+https://github.com/example/c?rev=aaa#aaa"
        g2 = "git+https://github.com/example/c?rev=bbb#bbb"
        a = ecc.closure(ecc.parse_lock(lock(pkg("signer-enclave", "0.1.0", deps=["c"]), pkg("c", "0.3.0", g1))), "signer-enclave")
        b = ecc.closure(ecc.parse_lock(lock(pkg("signer-enclave", "0.1.0", deps=["c"]), pkg("c", "0.3.0", g2))), "signer-enclave")
        self.assertNotEqual(a, b)

    def test_path_packages_are_keyed_as_path_and_source_qualified_deps_resolve(self):
        text = lock(
            pkg("signer-enclave", "0.1.0", deps=[f"c 0.3.0 ({REG})", "local"]),
            pkg("c", "0.3.0", REG),
            pkg("c", "0.3.0", "git+https://x/c#deadbeef"),   # same name+version, other source
            pkg("local", "0.0.1"),                            # workspace/path dep
        )
        got = ecc.closure(ecc.parse_lock(text), "signer-enclave")
        self.assertEqual(got, [f"c 0.3.0 ({REG})", "local 0.0.1 (path)"])

    def test_malformed_package_block_is_refused(self):
        text = lock(pkg("signer-enclave", "0.1.0", deps=["c"]), "[[package]]\nname = \"c\"\n")
        with self.assertRaises(ValueError):
            ecc.parse_lock(text)

    def test_malformed_dependency_entry_is_refused(self):
        text = lock(pkg("signer-enclave", "0.1.0", deps=["c 1.0.0 (x) extra"]))
        with self.assertRaises(ValueError):
            ecc.parse_lock(text)

    def test_missing_root_is_refused(self):
        with self.assertRaises(ValueError):
            ecc.closure(ecc.parse_lock(lock(pkg("other", "1.0.0", REG))), "signer-enclave")

    def test_split_only_at_line_start(self):
        text = lock(pkg("signer-enclave", "0.1.0", deps=["c"]), pkg("c", "0.3.0", REG)) + '\n# mention of [[package]] in a comment\n'
        self.assertEqual(ecc.closure(ecc.parse_lock(text), "signer-enclave"), [f"c 0.3.0 ({REG})"])


class SnapshotRoundTrip(unittest.TestCase):
    def test_write_then_check_ok_then_drift_fails(self):
        with tempfile.TemporaryDirectory() as d:
            lockfile = Path(d) / "Cargo.lock"
            snap = Path(d) / "CLOSURE.lock"
            lockfile.write_text(lock(pkg("signer-enclave", "0.1.0", deps=["c"]), pkg("c", "0.3.0", REG)), encoding="utf-8")
            self.assertEqual(ecc.run(lockfile, snap, write=True), 0)
            body = snap.read_text(encoding="utf-8")
            self.assertIn(f"c 0.3.0 ({REG})", body)
            self.assertTrue(body.startswith("#"), "header preserved/created")
            self.assertEqual(ecc.run(lockfile, snap, write=False), 0)
            # drift: bump c
            lockfile.write_text(lock(pkg("signer-enclave", "0.1.0", deps=["c"]), pkg("c", "0.4.0", REG)), encoding="utf-8")
            self.assertEqual(ecc.run(lockfile, snap, write=False), 1)

    def test_missing_paths_are_controlled_errors(self):
        with tempfile.TemporaryDirectory() as d:
            with self.assertRaises(OSError):
                ecc.run(Path(d) / "nope.lock", Path(d) / "snap", write=False)
            lockfile = Path(d) / "Cargo.lock"
            lockfile.write_text(lock(pkg("signer-enclave", "0.1.0")), encoding="utf-8")
            with self.assertRaises(OSError):
                ecc.run(lockfile, Path(d) / "missing-snapshot", write=False)


if __name__ == "__main__":
    unittest.main()
